name: Webapp release (service 1)

on:
  push:
    branches: [ main ]
    paths: [ 'src/Arda.WebApp/**' ]
  workflow_dispatch:
  
env:
  PROJECT_PATH: 'src/Arda.WebApp/Arda.WebApp.sln'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 9.0.*
        source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        
    - name: Install dependencies
      run: dotnet restore ${{ env.PROJECT_PATH }}
      
    - name: Build
      run: dotnet build ${{ env.PROJECT_PATH }} --configuration Release --no-restore
      
    - name: Test
      run: dotnet test ${{ env.PROJECT_PATH }} --no-restore --verbosity normal

    - name: Publish
      run: dotnet publish ${{ env.PROJECT_PATH }} --configuration Release --no-restore -o app/publish /p:UseAppHost=false

    - name: Publish artifact
      uses: actions/upload-artifact@v4
      with:
        name: main-app
        path: app/publish

  terraform-plan:
    needs: build-and-test
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - name: Terraform plan
        run: echo "Terraform plan"

  deploy-to-dev:
    needs: terraform-plan
    runs-on: ubuntu-latest
    environment:
      name: dev

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: main-app

    - name: Deploy to Dev server
      run: echo "Deploying to Dev server..."

  deploy-to-prod:
    if: github.ref == 'refs/heads/main'
    needs: deploy-to-dev
    runs-on: ubuntu-latest
    environment:
      name: prod

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: main-app

    - name: Deploy to Prod server
      run: echo "Deploying to Prod server..."

  create-release:
    if: github.ref == 'refs/heads/main'
    needs: deploy-to-prod
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: main-app
          path: dist/main-app

      - name: Create zip from artifact
        run: |
          mkdir -p dist
          cd dist/main-app
          zip -r ../webapp-v1.0.${{ github.run_number }}.zip ./
          cd ../..

      - name: Create release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: webapp-v1.0.${{ github.run_number }}
          release_name: Web app release v1.0.${{ github.run_number }}
          draft: false
          prerelease: false
          
      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: dist/webapp-v1.0.${{ github.run_number }}.zip
          asset_name: webapp-v1.0.${{ github.run_number }}.zip
          asset_content_type: application/zip
